[package]
name = "rustberg-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rustberg-server"
path = "src/main.rs"

[dependencies]
rustberg-core.workspace = true
rustberg-metastore.workspace = true
rustberg-catalog.workspace = true
rustberg-optimizer.workspace = true
rustberg-logstore.workspace = true
tokio.workspace = true
axum.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
